from datetime import datetime, timezone
from typing import List, Optional
from pydantic import BaseModel, Field


class ChatMessage(BaseModel):
    """Schema for an individual chat message in history."""

    role: str = Field(..., description="Message author role: 'user' or 'assistant'")
    content: str = Field(..., description="Content of the message")
    timestamp: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc),
        description="Timestamp when message was recorded in UTC",
    )


class ChatRequest(BaseModel):
    """Schema for chat input request."""

    message: str = Field(..., min_length=1, description="User input message for ORCA Brain")
    session_id: Optional[str] = Field(
        default=None,
        description="Optional unique session identifier. A new UUID is generated if omitted.",
    )


class ChatResponse(BaseModel):
    """Schema for chat response."""

    response: str = Field(..., description="Response generated by ORCA Brain")
    session_id: str = Field(..., description="Active session identifier")
    turns_count: int = Field(..., description="Total message turns stored in active session")


class SessionHistoryResponse(BaseModel):
    """Schema for retrieving a session's message history."""

    session_id: str
    messages: List[ChatMessage]
    total_messages: int


class SessionDeleteResponse(BaseModel):
    """Schema for session deletion/reset confirmation."""

    session_id: str
    status: str = "deleted"
    message: str = "Session conversation history cleared successfully"
