from enum import Enum
from typing import Any, Dict, Optional
from pydantic import BaseModel, Field


class IntentType(str, Enum):
    """Supported ORCA Brain intent types."""

    FISHING_POTENTIAL = "fishing_potential"
    MARINE_RISK = "marine_risk"
    HISTORICAL_PRODUCTIVITY = "historical_productivity"
    MARINE_SUITABILITY = "marine_suitability"
    OCEAN_ANALYSIS = "ocean_analysis"
    PFZ_ANALYSIS = "pfz_analysis"
    ROUTE_OPTIMIZATION = "route_optimization"
    MARINE_SAFETY = "marine_safety"
    WEATHER_INFORMATION = "weather_information"
    GENERAL_ORCA_CHAT = "general_orca_chat"
    MISSING_INFORMATION = "missing_information"
    UNKNOWN = "unknown"


class PlanRequest(BaseModel):
    """Schema for requesting an intent plan."""

    message: str = Field(..., min_length=1, description="User input query to plan and classify")
    session_id: Optional[str] = Field(default=None, description="Optional session identifier")


class PlanResponse(BaseModel):
    """Structured plan and routing decision generated by ORCA Brain."""

    intent: str = Field(..., description="Classified intent name")
    tool: Optional[str] = Field(default=None, description="Target tool identifier mapped from intent")
    confidence: float = Field(default=1.0, ge=0.0, le=1.0, description="Routing confidence score")
    needs_location: bool = Field(default=False, description="Flag indicating if location is required but missing")
    needs_date: bool = Field(default=False, description="Flag indicating if date/time is required")
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Extracted parameters (e.g. location, date, vessel, target_species)",
    )
