from typing import Dict, List, Optional
from pydantic import BaseModel, Field


class TranscribeResponse(BaseModel):
    """Structured response for speech-to-text transcription."""

    text: str = Field(..., description="Original-language transcription of spoken content")
    language: Optional[str] = Field(None, description="Detected or specified ISO language code (e.g., 'mr', 'hi', 'en')")
    confidence: Optional[float] = Field(None, description="Language probability or transcription confidence score (0.0 to 1.0), null if unavailable")
    duration: Optional[float] = Field(None, description="Estimated duration of the input audio in seconds")
    processing_time: Optional[float] = Field(None, description="Server-side transcription processing time in seconds")


class STTModelInfoResponse(BaseModel):
    """Metadata describing the active STT engine and capabilities."""

    engine: str = Field("faster-whisper", description="Underlying speech recognition engine")
    model_name: str = Field(..., description="Active Whisper model name / size (e.g. 'base', 'tiny', 'small')")
    device: str = Field(..., description="Execution compute device ('cpu' or 'cuda')")
    compute_type: str = Field(..., description="Quantization / compute precision ('int8', 'float32')")
    supported_languages: List[str] = Field(..., description="List of officially supported ISO language codes")


class SynthesizeRequest(BaseModel):
    """Request payload for text-to-speech synthesis."""

    text: str = Field(
        ...,
        min_length=1,
        max_length=2000,
        description="Original text to synthesize into spoken audio (e.g., Marathi, Hindi, English, code-mixed)",
        examples=["नमस्कार Prajwal, आजची समुद्राची परिस्थिती तपासतो."],
    )
    language: Optional[str] = Field(
        None,
        description="Target ISO language code (e.g., 'mr', 'hi', 'en', 'gu', 'ta', 'te', 'kn', 'ml', 'bn', 'ur')",
        examples=["mr"],
    )
    voice: Optional[str] = Field(
        None,
        description="Optional explicit voice identifier (e.g., 'mr-IN-AarohiNeural', 'hi-IN-SwaraNeural')",
    )
    gender: Optional[str] = Field(
        "female",
        description="Preferred voice gender ('female' or 'male')",
    )
    rate: Optional[str] = Field(
        "+0%",
        description="Speaking rate adjustment (e.g. '+0%', '+10%', '-10%')",
    )
    pitch: Optional[str] = Field(
        "+0Hz",
        description="Voice pitch adjustment (e.g. '+0Hz', '+5Hz', '-5Hz')",
    )


class TTSModelInfoResponse(BaseModel):
    """Metadata describing active Text-to-Speech engine and voice catalog."""

    engine: str = Field(..., description="Active TTS provider/engine (e.g. 'edge-tts')")
    default_language: str = Field(..., description="Default fallback language code")
    default_voice: str = Field(..., description="Default primary neural voice")
    supported_languages: List[str] = Field(..., description="List of officially supported ISO language codes")
    available_voices: Dict[str, List[str]] = Field(..., description="Dictionary mapping language codes to available voice IDs")


class VoicePipelineMetrics(BaseModel):
    """Latency metrics for each stage in the voice pipeline."""

    stt_duration_s: float = Field(..., description="Speech-to-Text inference duration in seconds")
    brain_duration_s: float = Field(..., description="ORCA Brain generation duration in seconds")
    tts_duration_s: float = Field(..., description="Text-to-Speech synthesis duration in seconds")
    total_duration_s: float = Field(..., description="End-to-end total pipeline duration in seconds")


class VoicePipelineResponse(BaseModel):
    """Structured response for end-to-end voice pipeline (STT -> Brain -> TTS)."""

    session_id: str = Field(..., description="Active conversation session ID")
    transcript: str = Field(..., description="Transcribed text from user's spoken audio")
    detected_language: Optional[str] = Field(None, description="Language detected or specified during STT")
    response_text: str = Field(..., description="Natural response generated by ORCA Brain (Qwen3-8B)")
    response_language: str = Field(..., description="Language used for synthesized audio")
    audio_base64: str = Field(..., description="Base64-encoded synthesized MP3 audio data")
    audio_format: str = Field("audio/mpeg", description="Audio MIME format")
    metrics: VoicePipelineMetrics = Field(..., description="Latency breakdown for each pipeline stage")


class VoicePipelineErrorDetail(BaseModel):
    """Structured error payload indicating the exact failed pipeline stage."""

    stage: str = Field(..., description="Failed pipeline stage ('stt', 'brain', 'tts', 'pipeline')")
    error: str = Field(..., description="Short error classification")
    message: str = Field(..., description="Human-readable error description")

